### PR TITLE
Implement dashboard with file system

### LINKED ISSUE #1004: Feature request: folder level in file upload page
In the uploaded documents page, it would be helpful if we add a folder level, so that it would be easier for users to retrieve files when they've uploaded lots of files. A searching/filter/label feature will also help.

image

### PR DESCRIPTION
**Pull request by chetbae**
closes #1004. 

Dashboard that allows users to create folders to categorize and organize documents.

[neon-chetbae.vercel.app](http://neon-chetbae.vercel.app/)

### CODE REVIEW

**Comment by chetbae** [comment]
closes #1040 [101e238](https://github.com/DDMAL/Neon/pull/1047/commits/101e238702bde2568d65dd175b69e6dc543b1925)
closes #1041 [de779a0](https://github.com/DDMAL/Neon/pull/1047/commits/de779a0a82039f17e1ecb222ecc51d426baccd47)
closes #1042 [0e34f67](https://github.com/DDMAL/Neon/pull/1047/commits/0e34f674c2bc89294ac726e5724141f91e2292b6)
closes #1043 [186947b](https://github.com/DDMAL/Neon/pull/1047/commits/186947b34cffc654f8dfe8420444c0720022c320)
closes #1044 [af33b22](https://github.com/DDMAL/Neon/pull/1047/commits/af33b22b2d90de82ab10c01708278c62066a5915) and [76faf99](https://github.com/DDMAL/Neon/pull/1047/commits/76faf99efdb582efb3be077546dc00951dfb7b0a)
closes #1045 ...
closes #1046 ...

**Comment by chetbae** [comment]
Ready to present! Just need to rebase to develop. 

Nice to haves: sorting, multiple drag, move contextmenu

**Comment by chetbae** [comment]
## Red: 🆘
- [x] Cannot add new folder in empty parent folder 📁🚫
- [x] Move-to from contextmenu 🚗💨
- [x] Improved error messages for dropping folders 

## Yellow: ⚠️
- [ ] Styling/icon indicating folders are folders and files are files 🙈
- [ ] Multiple Drag 👯‍♀️

## Green: 💹
- [ ] Sorting dashboard by name or date 📚
- [ ] History stack: undo/redo ...(something like `{ path: IFolder array, state: IFolder root clone }`) 🧠

**Comment by chetbae** [comment]
https://neon-aibobgz7p-chetbae.vercel.app/dashboard.html

Snapshot of the full pr! Few things not implemented such as sorting and multiple drag, which were not absolutely necessary but a nice user experience for the folder system. Would love to keep working this on the side while developing VIM though! 

@JoyfulGen @yinanazhou @cadagong How does this look to merge into prod?

**Comment by chetbae** [comment]
P.S. I tested going from develop (flat dashboard) with uploaded files in pouchDB → to dashboard-folder-impl (file system). Previous uploads go to the root folder.

The code for the transfer is in `FileSystemManager.ts` line 25, the logic goes like this:
```
if file-system state exists in local storage:
    load local storage state
else:
    create new root folder
    add samples folder to root
    get previous uploads from pouch db (if any)
    load newly created root folder
```

So hundreds of corrected folios won't be lost! If neon's domain ever changes, that's a different problem.

**Comment by JoyfulGen** [comment]
> @JoyfulGen @yinanazhou @cadagong How does this look to merge into prod?

It looks fantastic! Everything works very smoothly and it's an excellent system thank you :)))

**Review by yinanazhou — APPROVED** [review]
Looks good!

**Pull request merged**
